import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'
import { useRouter } from 'next/router';

export default function Home({ results }) {

  const router = useRouter()
  const id = results.city
  const seeDetails = () => {
    router.push(`/city/${id}`)
  }

  return (
    <div className="background">
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Image className="image" src="/icons/left.svg" width="300px" height=""/>
        <MainSection>
          <Image src="/icons/logo.svg" width="" height="100px"/>
          <p>Search weather condition for...</p>
          <City>
            <Image src="/icons/location.svg" width="50px" height=""/>
            <h1>{results.city}</h1>
          </City>
          <p>...or any other place</p>
          <Button onClick={seeDetails}>Start</Button>
        </MainSection>
        <Image className="image" src="/icons/right.svg" width="300px" height=""/>
      </Container>
    </div>
  )
}

export async function getServerSideProps() {
  const data = await fetch(`https://geolocation-db.com/json/${GEO_KEY}`)
      .then(response => response.json())
  return {
      props: {
          results: data
      }
  }
}


const Container = styled.div`
  display: flex;
  justify-content: space-evenly;
  
`

const MainSection = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: space-evenly;
  align-items: center;
  width:550px;
  height: 650px;
  background: rgb(86,115,140);
  background: linear-gradient(180deg, rgba(86,115,140,0.5) 0%, rgba(8,51,89,0.5) 50%);
  border-radius: 25px;

  p {
    font-size: 20px;
    font-weight: 200;
    color: #9AC1D9;
  }

  @media (max-width: 980px) {
    background: none;
    height: 550px;
  }

`

const City = styled.div`
  display: inline-flex;
  justify-content: center;
  align-items: center;
  width: 300px;

  h1 {
    font-size: 50px;
    margin-left: 20px;
  }
`

const Button = styled.button`
  width: 200px;
  height: 50px;
  border-radius: 10px;
  border: none;
  font-size: 25px;
  cursor: pointer;
  font-weight: 600;
  transition: 100ms ease-in-out;

  &:hover {
    opacity: 0.9;
  }
`
